### TASK 02 – TRUY VẤN & THỐNG KÊ MÔ TẢ

#### IMPORT & LOAD DỮ LIỆU SẠCH

In [1]:
import pandas as pd
import numpy as np

menu = pd.read_csv('../data_clean/menu_clean.csv')
order = pd.read_csv('../data_clean/order_log_clean.csv')
cost = pd.read_csv('../data_clean/cost_raw_material_clean.csv')

print("Menu:")
display(menu.head())

print("Order:")
display(order.head())

print("COST:")
display(cost.head())

Menu:

  product_id  product_name    price
0       CF01    Ca Phe Den  45000.0
1       CF02    Ca Phe Sua  35000.0
2       CF03      Bac  Xiu  35000.0
3       CF04       Tra Dao  45000.0
4       CF05  Sinh To Xoai     30.0

Order:

  order_id product_id           order_time  qty
0   OD2002       CF03  2024-01-01 14:12:00  2.0
1   OD2003       CF03  2024-01-01 06:16:00  2.0
2   OD2004       CF02  2024-01-01 04:55:00  1.0
3   OD2006       CF02  2024-01-01 06:56:00  3.0
4   OD2009       CF06                  NaN  1.0

COST:

  product_id  unit_cost
0       CF01     8000.0
1       CF02    15000.0
2       CF03        NaN
3       CF04     9000.0
4       CF05    15000.0

#### XỬ LÝ THỜI GIAN ORDER (NGÀY – GIỜ)

In [2]:
order['order_time'] = pd.to_datetime(order['order_time'], errors='coerce')

order['hour'] = order['order_time'].dt.hour
order['date'] = order['order_time'].dt.date

print("ORDER SAU KHI TÁCH NGÀY & GIỜ:")
display(order[['order_time', 'hour', 'date']].head())

ORDER SAU KHI TÁCH NGÀY & GIỜ:

           order_time  hour        date
0 2024-01-01 14:12:00  14.0  2024-01-01
1 2024-01-01 06:16:00   6.0  2024-01-01
2 2024-01-01 04:55:00   4.0  2024-01-01
3 2024-01-01 06:56:00   6.0  2024-01-01
4                 NaT   NaN         NaT