### IMPORT & ĐỌC DỮ LIỆU

In [ ]:
import pandas as pd

menu = pd.read_csv("../data_clean/menu_clean.csv")
order = pd.read_csv("../data_clean/order_log_clean.csv")
cost = pd.read_csv("../data_clean/cost_raw_material_clean.csv")

print("MENU:")
display(menu.head())

print("ORDER:")
display(order.head())

print("COST:")
display(cost.head())

display(cost.head())

MENU:

  product_id  product_name    price
0       CF01    Ca Phe Den  45000.0
1       CF02    Ca Phe Sua  35000.0
2       CF03      Bac  Xiu  35000.0
3       CF04       Tra Dao  45000.0
4       CF05  Sinh To Xoai     30.0

ORDER:

  order_id product_id           order_time  qty
0   OD2002       CF03  2024-01-01 14:12:00  2.0
1   OD2003       CF03  2024-01-01 06:16:00  2.0
2   OD2004       CF02  2024-01-01 04:55:00  1.0
3   OD2006       CF02  2024-01-01 06:56:00  3.0
4   OD2009       CF06                  NaN  1.0

COST:

  product_id  unit_cost
0       CF01     8000.0
1       CF02    15000.0
2       CF03        NaN
3       CF04     9000.0
4       CF05    15000.0

  product_id  unit_cost
0       CF01     8000.0
1       CF02    15000.0
2       CF03        NaN
3       CF04     9000.0
4       CF05    15000.0

### MERGE MENU VỚI ORDER

In [ ]:
order_menu = order.merge(
    menu,
    on="product_id",
    how="left",
    indicator=True
)

print("KẾT QUẢ MERGE ORDER + MENU:")
display(order_menu.head())

print("THỐNG KÊ TRẠNG THÁI MERGE:")
print(order_menu["_merge"].value_counts())

KẾT QUẢ MERGE ORDER + MENU:

  order_id product_id           order_time  qty  product_name    price _merge
0   OD2002       CF03  2024-01-01 14:12:00  2.0      Bac  Xiu  35000.0   both
1   OD2003       CF03  2024-01-01 06:16:00  2.0      Bac  Xiu  35000.0   both
2   OD2004       CF02  2024-01-01 04:55:00  1.0    Ca Phe Sua  35000.0   both
3   OD2006       CF02  2024-01-01 06:56:00  3.0    Ca Phe Sua  35000.0   both
4   OD2009       CF06                  NaN  1.0  Matcha Latte  35000.0   both

THỐNG KÊ TRẠNG THÁI MERGE:
_merge
both          63
left_only      0
right_only     0
Name: count, dtype: int64

### MERGE THÊM VỚI COST

In [ ]:
order_full = order_menu.merge(
    cost,
    on="product_id",
    how="left",
    indicator="cost_merge"
)

print("DỮ LIỆU SAU KHI MERGE THÊM COST:")
display(order_full.head())

print("THỐNG KÊ TRẠNG THÁI MERGE COST:")
print(order_full["cost_merge"].value_counts())

DỮ LIỆU SAU KHI MERGE THÊM COST:

,order_id,product_id,order_time,qty,product_name,price,_merge,unit_cost,cost_merge
0,OD2002,CF03,2024-01-01 14:12:00,2.0,Bac Xiu,35000.0,both,NaN,both
1,OD2003,CF03,2024-01-01 06:16:00,2.0,Bac Xiu,35000.0,both,NaN,both
2,OD2004,CF02,2024-01-01 04:55:00,1.0,Ca Phe Sua,35000.0,both,15000.0,both
3,OD2006,CF02,2024-01-01 06:56:00,3.0,Ca Phe Sua,35000.0,both,15000.0,both
4,OD2009,CF06,NaN,1.0,Matcha Latte,35000.0,both,9000.0,both

THỐNG KÊ TRẠNG THÁI MERGE COST:
cost_merge
both          63
left_only      0
right_only     0
Name: count, dtype: int64

### PHÁT HIỆN MISMACTH HOẶC MÓN KHÔNG CÓ COST

In [ ]:
order_missing_menu = order_menu[order_menu["_merge"] == "left_only"]

print("CÁC ORDER KHÔNG CÓ THÔNG TIN MENU:")
display(order_missing_menu)

CÁC ORDER KHÔNG CÓ THÔNG TIN MENU:

Empty DataFrame
Columns: [order_id, product_id, order_time, qty, product_name, price, _merge]
Index: []

### XUẤT FILE DỮ LIỆU HOÀN CHỈNH SAU KHI MERGE

In [13]:
order_full.to_csv(
    "full_data.csv",
    index=False,
)
print("Đã xuất file dữ liệu hoàn chỉnh sau khi merge: full_data.csv")

Đã xuất file dữ liệu hoàn chỉnh sau khi merge: full_data.csv