### GroupBy & Tổng hợp

#### IMPORT THƯ VIỆN & ĐỌC DỮ LIỆU

In [1]:
import pandas as pd
import numpy as np

menu = pd.read_csv("../data_clean/menu_clean.csv")
order = pd.read_csv("../data_clean/order_log_clean.csv")
cost = pd.read_csv("../data_clean/cost_raw_material_clean.csv")

print("MENU:")
display(menu.head())

print("ORDER:")
display(order.head())

print("COST:")
display(cost.head())

MENU:

  product_id  product_name    price
0       CF01    Ca Phe Den  45000.0
1       CF02    Ca Phe Sua  35000.0
2       CF03      Bac  Xiu  35000.0
3       CF04       Tra Dao  45000.0
4       CF05  Sinh To Xoai     30.0

ORDER:

  order_id product_id           order_time  qty
0   OD2002       CF03  2024-01-01 14:12:00  2.0
1   OD2003       CF03  2024-01-01 06:16:00  2.0
2   OD2004       CF02  2024-01-01 04:55:00  1.0
3   OD2006       CF02  2024-01-01 06:56:00  3.0
4   OD2009       CF06                  NaN  1.0

COST:

  product_id  unit_cost
0       CF01     8000.0
1       CF02    15000.0
2       CF03        NaN
3       CF04     9000.0
4       CF05    15000.0

#### MERGE ORDER VỚI MENU

In [2]:
order_menu = order.merge(
    menu[['product_id', 'product_name', 'price']],
    on='product_id',
    how='left'
)

order_menu['revenue'] = order_menu['qty'] * order_menu['price']

print("ORDER SAU KHI MERGE MENU:")
display(order_menu.head())

ORDER SAU KHI MERGE MENU:

,order_id,product_id,order_time,qty,product_name,price,revenue
0,OD2002,CF03,2024-01-01 14:12:00,2.0,Bac Xiu,35000.0,70000.0
1,OD2003,CF03,2024-01-01 06:16:00,2.0,Bac Xiu,35000.0,70000.0
2,OD2004,CF02,2024-01-01 04:55:00,1.0,Ca Phe Sua,35000.0,35000.0
3,OD2006,CF02,2024-01-01 06:56:00,3.0,Ca Phe Sua,35000.0,105000.0
4,OD2009,CF06,NaN,1.0,Matcha Latte,35000.0,35000.0

#### MERGE THÊM COST & TÍNH LỢI NHUẬN

In [3]:
order_full = order_menu.merge(
    cost[['product_id', 'unit_cost']],
    on='product_id',
    how='left'
)

order_full['profit'] = order_full['price'] - order_full['unit_cost']

print("ORDER SAU KHI GỘP COST & TÍNH LỢI NHUẬN:")
display(order_full.head())

ORDER SAU KHI GỘP COST & TÍNH LỢI NHUẬN:

,order_id,product_id,order_time,qty,product_name,price,revenue,unit_cost,profit
0,OD2002,CF03,2024-01-01 14:12:00,2.0,Bac Xiu,35000.0,70000.0,NaN,NaN
1,OD2003,CF03,2024-01-01 06:16:00,2.0,Bac Xiu,35000.0,70000.0,NaN,NaN
2,OD2004,CF02,2024-01-01 04:55:00,1.0,Ca Phe Sua,35000.0,35000.0,15000.0,20000.0
3,OD2006,CF02,2024-01-01 06:56:00,3.0,Ca Phe Sua,35000.0,105000.0,15000.0,20000.0
4,OD2009,CF06,NaN,1.0,Matcha Latte,35000.0,35000.0,9000.0,26000.0